# Generated by Django 4.1.6 on 2023-02-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=500, unique=True)),
                ('answer', models.CharField(default='', max_length=100)),
                ('category', models.CharField(default='', max_length=100)),
                ('level', models.CharField(default='', max_length=100)),
                ('wrong_answers', models.JSONField(default=[], null=True)),
            ],
        ),
    ]
